version: '3'

services:
  proxy:
    build: ./proxy
    image: ohmcar/proxy
    ports:
      - "9000:9000"
      - "80:9000"
    container_name: proxy
    restart: on-failure
    volumes:
      - "./proxy:/usr/src/proxy"
    environment:
      - servicePort=8080
  nodejsapp1:
    build: .
    image: ohmcar/nodejsapp1
    container_name: nodejsapp1
    restart: on-failure
    volumes:
      - ".:/usr/src/nodejsApp"
    depends_on:
      - postgres
    environment:
      - service_name=nodejsapp1
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres

  nodejsapp2:
    build: .
    image: ohmcar/nodejsapp2
    container_name: nodejsapp2
    restart: on-failure
    volumes:
      - ".:/usr/src/nodejsApp"
    depends_on:
      - postgres
    environment:
      - service_name=nodejsapp2
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres

  nodejsapp3:
    build: .
    image: ohmcar/nodejsapp3
    container_name: nodejsapp3
    restart: on-failure
    volumes:
      - ".:/usr/src/nodejsApp"
    depends_on:
      - postgres
    environment:
      - service_name=nodejsapp3
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    volumes:
      - /var/lib/docker/volumes/persistence/_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
